name: Build and Test

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: macos-latest
            name: macOS
          - os: windows-latest
            name: Windows (MinGW)
            toolchain: mingw
          - os: windows-latest
            name: Windows (MSVC)
            toolchain: msvc
          - os: windows-11-arm
            name: Windows ARM
            toolchain: mingw
      fail-fast: false
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y \
            build-essential \
            libeigen3-dev \
            catch2

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install eigen catch2

      - name: Install dependencies (Windows MinGW)
        if: runner.os == 'Windows' && matrix.toolchain == 'mingw'
        run: |
          choco install mingw
          vcpkg install eigen3 catch2 --triplet x64-mingw-dynamic

      - name: Install dependencies (Windows MSVC)
        if: runner.os == 'Windows' && matrix.toolchain == 'msvc'
        run: |
          vcpkg install eigen3 catch2 libomp --triplet x64-windows

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2.1
        with:
          cmake-version: "3.25"

      - name: Configure CMake (Windows MinGW)
        if: runner.os == 'Windows' && matrix.toolchain == 'mingw'
        run: cmake -B build -S . -DBUILD_TESTING=ON -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-mingw-dynamic

      - name: Configure CMake (Windows MSVC)
        if: runner.os == 'Windows' && matrix.toolchain == 'msvc'
        run: cmake -B build -S . -DBUILD_TESTING=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Configure CMake (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake -B build -S . -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build

      - name: Install
        run: ${{ runner.os == 'Windows' && 'cmake --install build' || 'sudo cmake --install build' }}

      - name: Test
        run: ctest --test-dir build --output-on-failure
